using System.Collections.Generic;
using NUnit.Framework;
namespace EspGisViewer.DiffTests.Tests.Auto
{
    public class AutoWfsTests
    {
        public static void Main()
        {
            var test = new AutoWfsTests();
            test.AutoDescribeFeatureTypeTests();
            test.AutoGetFeatureTests();
        }

        public void AutoDescribeFeatureTypeTests()
        {
            new AutogeneratedTests("/wfs?request=DescribeFeatureType&service=WFS&version=2.0.0", DescribeFeatureTypeParameterVariations).RunAutoTests();
        }

        public void AutoGetFeatureTests()
        {
            new AutogeneratedTests("/wfs?request=GetFeature&service=WFS&version=2.0.0", GetFeatureParameterVariations).RunAutoTests();
        }

        private static readonly Dictionary<string, string[]> GetFeatureParameterVariations = new Dictionary<string, string[]>
        {
            {
                "typenames", new [] {
                    null,                               // Parameter absent (test relies on 'typename' or error if both absent)
                    "plans",                            // Single valid typename
                    "plans,nonexistenttype",            // Mix of valid and non-existent (SUT should process 'plans')
                    "nonexistenttype1,nonexistenttype2" // Multiple non-existent (SUT should process, likely 0 features)
                }
            },

            {
                "typename", new [] {
                    null,                // Parameter absent
                    "plans",             // Single valid typename
                    ":plans",            // ESRI-style with leading colon
                    "nonexistenttype"    // Single non-existent typename
                }
            },

            {
                "outputformat", new [] {
                    null,       // Parameter absent (defaults to WFS XML/GML)
                    "GEOJSON",  // Valid GeoJSON format
                    "JSON"      // Invalid format (expect error)
                }
            },

            // 'bbox' parameter variations (minX,minY,maxX,maxY[,crs])
            {
                "bbox", new [] {
                    null,                                           // Parameter absent (no spatial filter)
                    "5,50,5.5,50.5",                                // Valid: Includes plan_id 101 (x=5.1, y=50.2)
                    "0,0,1,1",                                      // Valid: Excludes all 'plans' features
                    "6,51,6.5,51.5,urn:ogc:def:crs:EPSG::3857",     // Valid: 5-part BBOX with supported CRS (includes plan_id 102: x=6.3, y=51.4)
                    "10,20",                                        // Invalid: Too few values (expect error)
                    "10,20,abc,25",                                 // Invalid: Non-numeric value (expect error)
                    "10,20,15,25,urn:ogc:def:crs:EPSG::4326",       // Invalid: 5-part BBOX with unsupported CRS (expect error)
                    "10201525",                                     // Invalid: No commas (expect error)
                    "1,2,3,4,5,urn:ogc:def:crs:EPSG::3857"          // Invalid: Too many parts (6 parts, expect error as SUT expects 4 or 5)
                }
            },

            // 'count' parameter variations (max number of features to return)
            {
                "count", new [] {
                    "0",        // Valid: Request 0 features
                    "1",        // Valid: Request 1 feature
                    "3",        // Valid: Request all 3 'plans' features (from mock data)
                    "10",       // Valid: Request more features than available
                    "-1",       // Invalid: Negative count (expect error)
                    "abc"       // Invalid: Non-numeric count (expect error)
                }
            },

            // 'srsname' parameter variations (Spatial Reference System for output and BBOX if not specified in BBOX)
            {
                "srsname", new [] {
                    null,                               // Parameter absent (defaults to EPSG:3857)
                    "EPSG:3857",                        // Valid: Web Mercator
                    "EPSG:4326",                        // Valid: WGS 84
                    "EPSG:102100",                      // Valid: Alias for EPSG:3857
                    "urn:ogc:def:crs:EPSG::4326",       // Valid: URN for WGS 84
                    "urn:ogc:def:crs:EPSG::3857",       // Valid: URN for Web Mercator
                    "EPSG:900913"                       // Invalid: Unsupported SRS (expect error)
                }
            }
        };

        private static readonly Dictionary<string, string[]> DescribeFeatureTypeParameterVariations = new Dictionary<string, string[]>
        {
            {
                "typenames", new [] {
                    null,                               // Parameter absent (test relies on 'typename' or error if both absent)
                    "plans",                            // Single valid typename
                    "plans,nonexistenttype",            // Mix of valid and non-existent (SUT should process 'plans')
                    "nonexistenttype1,nonexistenttype2" // Multiple non-existent (SUT should process, likely 0 features)
                }
            },

            {
                "typename", new [] {
                    null,                // Parameter absent
                    "plans",             // Single valid typename
                    ":plans",            // ESRI-style with leading colon
                    "nonexistenttype"    // Single non-existent typename
                }
            }
        };
    }
}
