using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
namespace EspGisViewer.DiffTests.Tests.Auto
{
    public class AutogeneratedTests : DiffTests
    {

        private readonly string _path;
        private readonly Dictionary<string, string[]> _parameters;

        public AutogeneratedTests(string path, Dictionary<string, string[]> parameters)
        {
            _path = path;
            _parameters = parameters;
        }

        public void RunAutoTests()
        {
            var paths = new List<string>();
            GenerateParameterVariations(_path, _parameters, paths.Add);

            var startTime = DateTime.Now;
            var lastProgressUpdate = startTime;

            var resetEvents = new List<ManualResetEvent>();

            for (var index = 0; index < paths.Count; index++)
            {
                var index1 = index;
                var resetEvent = new ManualResetEvent(false);
                ThreadPool.QueueUserWorkItem(state =>
                {
                    var path = paths[index1];
                    var timeSinceLastUpdate = DateTime.Now - lastProgressUpdate;
                    if (timeSinceLastUpdate.TotalSeconds > 1)
                    {
                        var eta = TimeSpan.FromSeconds((DateTime.Now - startTime).TotalSeconds / (index1 + 1) * (paths.Count - index1 - 1));
                        var percent = (index1 + 1) / (double) paths.Count * 100;
                        Console.WriteLine($"Testing... ({index1 + 1}/{paths.Count}) {percent:0.00}% - ETA: {eta.Hours:D2}:{eta.Minutes:D2}:{eta.Seconds:D2}");
                        lastProgressUpdate = DateTime.Now;
                    }

                    AssertRequestEquals(path);

                    resetEvent.Set();
                });
                resetEvents.Add(resetEvent);
            }

            resetEvents.ForEach(e => e.WaitOne());
            var totalTime = DateTime.Now - startTime;
            Console.WriteLine($"{GetType().Name} auto tests completed in {totalTime.Hours:D2}:{totalTime.Minutes:D2}:{totalTime.Seconds:D2}");
        }

        private static void GenerateParameterVariations(string path, Dictionary<string, string[]> parameters, Action<string> outputPaths)
        {
            var anyKey = parameters.Keys.FirstOrDefault();
            if (anyKey == null)
            {
                outputPaths(path);
                return;
            }

            foreach (var value in parameters[anyKey])
            {
                var newPath = path;
                if (value != null)
                {
                    newPath += $"&{anyKey}={value}";
                }
                GenerateParameterVariations(newPath, parameters.Where(kvp => kvp.Key != anyKey).ToDictionary(kvp => kvp.Key, kvp => kvp.Value), outputPaths);
            }
        }

    }
}
